import img1 from "./../img/Ether.png"
import img2 from "./../img/Polygon 2.svg"
import img3 from "./../img/the-starinassets.svg"
const x1 = img1; 
const x2 = img2; 
const x3 = img3;
export const TableDataAssets = [
    {
        imgCrypto: x1,
        ImgAndName:"Img-And-Name",
        cNameCrypto: "name-crypto",
        nameCrypto: "Bitcoin",
        logoName:"BTC",
        Earn:"$38,755",
        OnOrders: "$38,755",
        CAvailableBalance:"AB-AvailableBalance",
        AvailableBalance:"2.52976876",
        SpanAvailableBalance:"≈ 111.63USD",
        ProfitLoss:"0.06%",
        cNameContainer:"container",
        imgPercentageArrow:x2,
        CGropBtn:"GropBtn",
        GropBtnDeposit:"Deposit",
        GropBtnWithdraw:"Withdraw",
        GropBtnTrade:"Trade",
        TheStar: x3,
        deposit:"/deposit",
        Withdraw:"/withdraw",
        Trade:"/trade"
    },
    {
        imgCrypto: x1,
        ImgAndName:"Img-And-Name",
        cNameCrypto: "name-crypto",
        nameCrypto: "Bitcoin",
        logoName:"BTC",
        Earn:"$38,755",
        OnOrders: "$38,755",
        CAvailableBalance:"AB-AvailableBalance",
        AvailableBalance:"2.52976876",
        SpanAvailableBalance:"≈ 111.63USD",
        ProfitLoss:"0.06%",
        cNameContainer:"container",
        imgPercentageArrow:x2,
        CGropBtn:"GropBtn",
        GropBtnDeposit:"Deposit",
        GropBtnWithdraw:"Withdraw",
        GropBtnTrade:"Trade",
        TheStar: x3,
        deposit:"/deposit",
        Withdraw:"/withdraw",
        Trade:"/trade"
    },
    {
        imgCrypto: x1,
        ImgAndName:"Img-And-Name",
        cNameCrypto: "name-crypto",
        nameCrypto: "Bitcoin",
        logoName:"BTC",
        Earn:"$38,755",
        OnOrders: "$38,755",
        CAvailableBalance:"AB-AvailableBalance",
        AvailableBalance:"2.52976876",
        SpanAvailableBalance:"≈ 111.63USD",
        ProfitLoss:"0.06%",
        cNameContainer:"container",
        imgPercentageArrow:x2,
        CGropBtn:"GropBtn",
        GropBtnDeposit:"Deposit",
        GropBtnWithdraw:"Withdraw",
        GropBtnTrade:"Trade",
        TheStar: x3,
        deposit:"/deposit",
        Withdraw:"/withdraw",
        Trade:"/trade"
    },
    {
        imgCrypto: x1,
        ImgAndName:"Img-And-Name",
        cNameCrypto: "name-crypto",
        nameCrypto: "Bitcoin",
        logoName:"BTC",
        Earn:"$38,755",
        OnOrders: "$38,755",
        CAvailableBalance:"AB-AvailableBalance",
        AvailableBalance:"2.52976876",
        SpanAvailableBalance:"≈ 111.63USD",
        ProfitLoss:"0.06%",
        cNameContainer:"container",
        imgPercentageArrow:x2,
        CGropBtn:"GropBtn",
        GropBtnDeposit:"Deposit",
        GropBtnWithdraw:"Withdraw",
        GropBtnTrade:"Trade",
        TheStar: x3,
        deposit:"/deposit",
        Withdraw:"/withdraw",
        Trade:"/trade"
    },
    {
        imgCrypto: x1,
        ImgAndName:"Img-And-Name",
        cNameCrypto: "name-crypto",
        nameCrypto: "Bitcoin",
        logoName:"BTC",
        Earn:"$38,755",
        OnOrders: "$38,755",
        CAvailableBalance:"AB-AvailableBalance",
        AvailableBalance:"2.52976876",
        SpanAvailableBalance:"≈ 111.63USD",
        ProfitLoss:"0.06%",
        cNameContainer:"container",
        imgPercentageArrow:x2,
        CGropBtn:"GropBtn",
        GropBtnDeposit:"Deposit",
        GropBtnWithdraw:"Withdraw",
        GropBtnTrade:"Trade",
        TheStar: x3,
        deposit:"/deposit",
        Withdraw:"/withdraw",
        Trade:"/trade"
    },
    {
        imgCrypto: x1,
        ImgAndName:"Img-And-Name",
        cNameCrypto: "name-crypto",
        nameCrypto: "Bitcoin",
        logoName:"BTC",
        Earn:"$38,755",
        OnOrders: "$38,755",
        CAvailableBalance:"AB-AvailableBalance",
        AvailableBalance:"2.52976876",
        SpanAvailableBalance:"≈ 111.63USD",
        ProfitLoss:"0.06%",
        cNameContainer:"container",
        imgPercentageArrow:x2,
        CGropBtn:"GropBtn",
        GropBtnDeposit:"Deposit",
        GropBtnWithdraw:"Withdraw",
        GropBtnTrade:"Trade",
        TheStar: x3,
        deposit:"/deposit",
        Withdraw:"/withdraw",
        Trade:"/trade"
    },
    {
        imgCrypto: x1,
        ImgAndName:"Img-And-Name",
        cNameCrypto: "name-crypto",
        nameCrypto: "Bitcoin",
        logoName:"BTC",
        Earn:"$38,755",
        OnOrders: "$38,755",
        CAvailableBalance:"AB-AvailableBalance",
        AvailableBalance:"2.52976876",
        SpanAvailableBalance:"≈ 111.63USD",
        ProfitLoss:"0.06%",
        cNameContainer:"container",
        imgPercentageArrow:x2,
        CGropBtn:"GropBtn",
        GropBtnDeposit:"Deposit",
        GropBtnWithdraw:"Withdraw",
        GropBtnTrade:"Trade",
        TheStar: x3,
        deposit:"/deposit",
        Withdraw:"/withdraw",
        Trade:"/trade"
    },
    {
        imgCrypto: x1,
        ImgAndName:"Img-And-Name",
        cNameCrypto: "name-crypto",
        nameCrypto: "Bitcoin",
        logoName:"BTC",
        Earn:"$38,755",
        OnOrders: "$38,755",
        CAvailableBalance:"AB-AvailableBalance",
        AvailableBalance:"2.52976876",
        SpanAvailableBalance:"≈ 111.63USD",
        ProfitLoss:"0.06%",
        cNameContainer:"container",
        imgPercentageArrow:x2,
        CGropBtn:"GropBtn",
        GropBtnDeposit:"Deposit",
        GropBtnWithdraw:"Withdraw",
        GropBtnTrade:"Trade",
        TheStar: x3,
        deposit:"/deposit",
        Withdraw:"/withdraw",
        Trade:"/trade"
    },
    {
        imgCrypto: x1,
        ImgAndName:"Img-And-Name",
        cNameCrypto: "name-crypto",
        nameCrypto: "Bitcoin",
        logoName:"BTC",
        Earn:"$38,755",
        OnOrders: "$38,755",
        CAvailableBalance:"AB-AvailableBalance",
        AvailableBalance:"2.52976876",
        SpanAvailableBalance:"≈ 111.63USD",
        ProfitLoss:"0.06%",
        cNameContainer:"container",
        imgPercentageArrow:x2,
        CGropBtn:"GropBtn",
        GropBtnDeposit:"Deposit",
        GropBtnWithdraw:"Withdraw",
        GropBtnTrade:"Trade",
        TheStar: x3,
        deposit:"/deposit",
        Withdraw:"/withdraw",
        Trade:"/trade"
    },
    {
        imgCrypto: x1,
        ImgAndName:"Img-And-Name",
        cNameCrypto: "name-crypto",
        nameCrypto: "Bitcoin",
        logoName:"BTC",
        Earn:"$38,755",
        OnOrders: "$38,755",
        CAvailableBalance:"AB-AvailableBalance",
        AvailableBalance:"2.52976876",
        SpanAvailableBalance:"≈ 111.63USD",
        ProfitLoss:"0.06%",
        cNameContainer:"container",
        imgPercentageArrow:x2,
        CGropBtn:"GropBtn",
        GropBtnDeposit:"Deposit",
        GropBtnWithdraw:"Withdraw",
        GropBtnTrade:"Trade",
        TheStar: x3,
        deposit:"/deposit",
        Withdraw:"/withdraw",
        Trade:"/trade"
    },
    {
        imgCrypto: x1,
        ImgAndName:"Img-And-Name",
        cNameCrypto: "name-crypto",
        nameCrypto: "Bitcoin",
        logoName:"BTC",
        Earn:"$38,755",
        OnOrders: "$38,755",
        CAvailableBalance:"AB-AvailableBalance",
        AvailableBalance:"2.52976876",
        SpanAvailableBalance:"≈ 111.63USD",
        ProfitLoss:"0.06%",
        cNameContainer:"container",
        imgPercentageArrow:x2,
        CGropBtn:"GropBtn",
        GropBtnDeposit:"Deposit",
        GropBtnWithdraw:"Withdraw",
        GropBtnTrade:"Trade",
        TheStar: x3,
        deposit:"/deposit",
        Withdraw:"/withdraw",
        Trade:"/trade"
    },
    
];