import img1 from "./../img/Curenceis.png";
import img2 from "./../img/Vector-X.svg"
const x1 = img1;
const x2 = img2;

export const TableTheOrders = [
    {
        Time: "2022/07/30 16:18:41",
        CAllPairs: "AB-AllPairs",
        AllPairs: "BTC/USDT",
        ImgAllPairs: x1,
        AllTypes: "Limit Order",
        BuySell: "Buy",
        PriceUSDT: "36,641.20",
        AmountBTC: "0.265622",
        Filled: "25%",
        Unfilled: "75%",
        Action: "Cancel",
        CAction: "AB-Action",
        ImgAction: x2,
    },
    {
        Time: "2022/07/30 16:18:41",
        CAllPairs: "AB-AllPairs",
        AllPairs: "BTC/USDT",
        ImgAllPairs: x1,
        AllTypes: "Limit Order",
        BuySell: "Buy",
        PriceUSDT: "36,641.20",
        AmountBTC: "0.265622",
        Filled: "25%",
        Unfilled: "75%",
        Action: "Cancel",
        CAction: "AB-Action",
        ImgAction: x2,
    },
    {
        Time: "2022/07/30 16:18:41",
        CAllPairs: "AB-AllPairs",
        AllPairs: "BTC/USDT",
        ImgAllPairs: x1,
        AllTypes: "Limit Order",
        BuySell: "Buy",
        PriceUSDT: "36,641.20",
        AmountBTC: "0.265622",
        Filled: "25%",
        Unfilled: "75%",
        Action: "Cancel",
        CAction: "AB-Action",
        ImgAction: x2,
    },
    {
        Time: "2022/07/30 16:18:41",
        CAllPairs: "AB-AllPairs",
        AllPairs: "BTC/USDT",
        ImgAllPairs: x1,
        AllTypes: "Limit Order",
        BuySell: "Buy",
        PriceUSDT: "36,641.20",
        AmountBTC: "0.265622",
        Filled: "25%",
        Unfilled: "75%",
        Action: "Cancel",
        CAction: "AB-Action",
        ImgAction: x2,
    },
    {
        Time: "2022/07/30 16:18:41",
        CAllPairs: "AB-AllPairs",
        AllPairs: "BTC/USDT",
        ImgAllPairs: x1,
        AllTypes: "Limit Order",
        BuySell: "Buy",
        PriceUSDT: "36,641.20",
        AmountBTC: "0.265622",
        Filled: "25%",
        Unfilled: "75%",
        Action: "Cancel",
        CAction: "AB-Action",
        ImgAction: x2,
    },
]