import img1 from "./../img/Ether.png"
import img2 from "./../img/Polygon 2.svg"
import img3 from "./../img/PriceLine.png"
import img4 from "./../img/Star-Icon.svg"
const x1 = img1; 
const x2 = img2; 
const x3 = img3; 
const x4 = img4; 
export const TableData = [
    {
        cpriclist: "priclist",
        number:"1",
        imgCrypto: x1,
        ImgAndName:"Img-And-Name",
        cNameCrypto: "name-crypto",
        nameCrypto: "Bitcoin",
        logoName:"BTC",
        Price:"$38,755",
        cNameContainer:"container",
        FirstPercentage:"3.36%",
        imgPercentageArrow:x2,
        SecondPercentage:"3.38%",
        MarketCap:"$390.6B",
        Volume:"$66.3T",
        CirculatingSupply: "19,087,425 BTC",
        cNameLine:"line",
        Last90Days:x3,
        CBtnTradePricList: "AB-BtnTradePricList",
        Action:"Trade",
        imgStar:x4
    },
    {
        cpriclist: "priclist",
        number:"1",
        imgCrypto: x1,
        ImgAndName:"Img-And-Name",
        cNameCrypto: "name-crypto",
        nameCrypto: "Bitcoin",
        logoName:"BTC",
        Price:"$38,755",
        cNameContainer:"container",
        FirstPercentage:"3.36%",
        imgPercentageArrow:x2,
        SecondPercentage:"3.38%",
        MarketCap:"$390.6B",
        Volume:"$66.3T",
        CirculatingSupply: "19,087,425 BTC",
        cNameLine:"line",
        Last90Days:x3,
        CBtnTradePricList: "AB-BtnTradePricList",
        Action:"Trade",
        imgStar:x4
    },
    {
        cpriclist: "priclist",
        number:"1",
        imgCrypto: x1,
        ImgAndName:"Img-And-Name",
        cNameCrypto: "name-crypto",
        nameCrypto: "Bitcoin",
        logoName:"BTC",
        Price:"$38,755",
        cNameContainer:"container",
        FirstPercentage:"3.36%",
        imgPercentageArrow:x2,
        SecondPercentage:"3.38%",
        MarketCap:"$390.6B",
        Volume:"$66.3T",
        CirculatingSupply: "19,087,425 BTC",
        cNameLine:"line",
        Last90Days:x3,
        CBtnTradePricList: "AB-BtnTradePricList",
        Action:"Trade",
        imgStar:x4
    },
    {
        cpriclist: "priclist",
        number:"1",
        imgCrypto: x1,
        ImgAndName:"Img-And-Name",
        cNameCrypto: "name-crypto",
        nameCrypto: "Bitcoin",
        logoName:"BTC",
        Price:"$38,755",
        cNameContainer:"container",
        FirstPercentage:"3.36%",
        imgPercentageArrow:x2,
        SecondPercentage:"3.38%",
        MarketCap:"$390.6B",
        Volume:"$66.3T",
        CirculatingSupply: "19,087,425 BTC",
        cNameLine:"line",
        Last90Days:x3,
        CBtnTradePricList: "AB-BtnTradePricList",
        Action:"Trade",
        imgStar:x4
    },
    {
        cpriclist: "priclist",
        number:"1",
        imgCrypto: x1,
        ImgAndName:"Img-And-Name",
        cNameCrypto: "name-crypto",
        nameCrypto: "Bitcoin",
        logoName:"BTC",
        Price:"$38,755",
        cNameContainer:"container",
        FirstPercentage:"3.36%",
        imgPercentageArrow:x2,
        SecondPercentage:"3.38%",
        MarketCap:"$390.6B",
        Volume:"$66.3T",
        CirculatingSupply: "19,087,425 BTC",
        cNameLine:"line",
        Last90Days:x3,
        CBtnTradePricList: "AB-BtnTradePricList",
        Action:"Trade",
        imgStar:x4
    },
    {
        cpriclist: "priclist",
        number:"1",
        imgCrypto: x1,
        ImgAndName:"Img-And-Name",
        cNameCrypto: "name-crypto",
        nameCrypto: "Bitcoin",
        logoName:"BTC",
        Price:"$38,755",
        cNameContainer:"container",
        FirstPercentage:"3.36%",
        imgPercentageArrow:x2,
        SecondPercentage:"3.38%",
        MarketCap:"$390.6B",
        Volume:"$66.3T",
        CirculatingSupply: "19,087,425 BTC",
        cNameLine:"line",
        Last90Days:x3,
        CBtnTradePricList: "AB-BtnTradePricList",
        Action:"Trade",
        imgStar:x4
    },
    {
        cpriclist: "priclist",
        number:"1",
        imgCrypto: x1,
        ImgAndName:"Img-And-Name",
        cNameCrypto: "name-crypto",
        nameCrypto: "Bitcoin",
        logoName:"BTC",
        Price:"$38,755",
        cNameContainer:"container",
        FirstPercentage:"3.36%",
        imgPercentageArrow:x2,
        SecondPercentage:"3.38%",
        MarketCap:"$390.6B",
        Volume:"$66.3T",
        CirculatingSupply: "19,087,425 BTC",
        cNameLine:"line",
        Last90Days:x3,
        CBtnTradePricList: "AB-BtnTradePricList",
        Action:"Trade",
        imgStar:x4
    },
    {
        cpriclist: "priclist",
        number:"1",
        imgCrypto: x1,
        ImgAndName:"Img-And-Name",
        cNameCrypto: "name-crypto",
        nameCrypto: "Bitcoin",
        logoName:"BTC",
        Price:"$38,755",
        cNameContainer:"container",
        FirstPercentage:"3.36%",
        imgPercentageArrow:x2,
        SecondPercentage:"3.38%",
        MarketCap:"$390.6B",
        Volume:"$66.3T",
        CirculatingSupply: "19,087,425 BTC",
        cNameLine:"line",
        Last90Days:x3,
        CBtnTradePricList: "AB-BtnTradePricList",
        Action:"Trade",
        imgStar:x4
    },
    {
        cpriclist: "priclist",
        number:"1",
        imgCrypto: x1,
        ImgAndName:"Img-And-Name",
        cNameCrypto: "name-crypto",
        nameCrypto: "Bitcoin",
        logoName:"BTC",
        Price:"$38,755",
        cNameContainer:"container",
        FirstPercentage:"3.36%",
        imgPercentageArrow:x2,
        SecondPercentage:"3.38%",
        MarketCap:"$390.6B",
        Volume:"$66.3T",
        CirculatingSupply: "19,087,425 BTC",
        cNameLine:"line",
        Last90Days:x3,
        CBtnTradePricList: "AB-BtnTradePricList",
        Action:"Trade",
        imgStar:x4
    },
    {
        cpriclist: "priclist",
        number:"1",
        imgCrypto: x1,
        ImgAndName:"Img-And-Name",
        cNameCrypto: "name-crypto",
        nameCrypto: "Bitcoin",
        logoName:"BTC",
        Price:"$38,755",
        cNameContainer:"container",
        FirstPercentage:"3.36%",
        imgPercentageArrow:x2,
        SecondPercentage:"3.38%",
        MarketCap:"$390.6B",
        Volume:"$66.3T",
        CirculatingSupply: "19,087,425 BTC",
        cNameLine:"line",
        Last90Days:x3,
        CBtnTradePricList: "AB-BtnTradePricList",
        Action:"Trade",
        imgStar:x4
    },
    {
        cpriclist: "priclist",
        number:"1",
        imgCrypto: x1,
        ImgAndName:"Img-And-Name",
        cNameCrypto: "name-crypto",
        nameCrypto: "Bitcoin",
        logoName:"BTC",
        Price:"$38,755",
        cNameContainer:"container",
        FirstPercentage:"3.36%",
        imgPercentageArrow:x2,
        SecondPercentage:"3.38%",
        MarketCap:"$390.6B",
        Volume:"$66.3T",
        CirculatingSupply: "19,087,425 BTC",
        cNameLine:"line",
        Last90Days:x3,
        CBtnTradePricList: "AB-BtnTradePricList",
        Action:"Trade",
        imgStar:x4
    },
    {
        cpriclist: "priclist",
        number:"1",
        imgCrypto: x1,
        ImgAndName:"Img-And-Name",
        cNameCrypto: "name-crypto",
        nameCrypto: "Bitcoin",
        logoName:"BTC",
        Price:"$38,755",
        cNameContainer:"container",
        FirstPercentage:"3.36%",
        imgPercentageArrow:x2,
        SecondPercentage:"3.38%",
        MarketCap:"$390.6B",
        Volume:"$66.3T",
        CirculatingSupply: "19,087,425 BTC",
        cNameLine:"line",
        Last90Days:x3,
        CBtnTradePricList: "AB-BtnTradePricList",
        Action:"Trade",
        imgStar:x4
    },
    {
        cpriclist: "priclist",
        number:"1",
        imgCrypto: x1,
        ImgAndName:"Img-And-Name",
        cNameCrypto: "name-crypto",
        nameCrypto: "Bitcoin",
        logoName:"BTC",
        Price:"$38,755",
        cNameContainer:"container",
        FirstPercentage:"3.36%",
        imgPercentageArrow:x2,
        SecondPercentage:"3.38%",
        MarketCap:"$390.6B",
        Volume:"$66.3T",
        CirculatingSupply: "19,087,425 BTC",
        cNameLine:"line",
        Last90Days:x3,
        CBtnTradePricList: "AB-BtnTradePricList",
        Action:"Trade",
        imgStar:x4
    },
];